server.port=8081

spring.datasource.url=${SERVICE_DB_URL}
spring.datasource.username=${SERVICE_DB_USERNAME}
spring.datasource.password=${SERVICE_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.cloud.gateway.server.webmvc.routes[0].id=restservice
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://restservice
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/restservice/**
spring.cloud.gateway.server.webmvc.routes[0].filters[0]=StripPrefix=2

spring.cloud.gateway.server.webmvc.routes[1].id=auth-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://auth-service
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/auth/**
spring.cloud.gateway.server.webmvc.routes[1].filters[0]=StripPrefix=2

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true